// シンタックスハイライトのカラーマップ（白背景用の濃い色）
export const colorMap = {
  'hljs-keyword': '#d73a49',      // 予約語 (dark red)
  'hljs-built_in': '#005cc5',     // 組み込み (dark blue)
  'hljs-type': '#d73a49',         // 型 (dark red)
  'hljs-literal': '#005cc5',      // リテラル (dark blue)
  'hljs-number': '#005cc5',       // 数値 (dark blue)
  'hljs-operator': '#d73a49',     // 演算子 (dark red)
  'hljs-punctuation': '#24292e',  // 句読点 (black)
  'hljs-property': '#005cc5',     // プロパティ (dark blue)
  'hljs-regexp': '#22863a',       // 正規表現 (dark green)
  'hljs-string': '#032f62',       // 文字列 (dark blue)
  'hljs-char.escape': '#032f62',  // エスケープ文字 (dark blue)
  'hljs-subst': '#24292e',        // 置換 (black)
  'hljs-symbol': '#e36209',       // シンボル (dark orange)
  'hljs-variable': '#e36209',     // 変数 (dark orange)
  'hljs-variable.language': '#d73a49', // 言語変数 (dark red)
  'hljs-variable.constant': '#005cc5', // 定数 (dark blue)
  'hljs-title': '#6f42c1',        // タイトル (dark purple)
  'hljs-title.class': '#e36209',  // クラス名 (dark orange)
  'hljs-title.function': '#6f42c1', // 関数名 (dark purple)
  'hljs-params': '#24292e',       // パラメータ (black)
  'hljs-comment': '#6a737d',      // コメント (gray)
  'hljs-doctag': '#6a737d',       // ドキュメントタグ (gray)
  'hljs-meta': '#6a737d',         // メタ (gray)
  'hljs-meta.prompt': '#6a737d',  // メタプロンプト (gray)
  'hljs-attr': '#005cc5',         // 属性 (dark blue)
  'hljs-attribute': '#005cc5',    // 属性 (dark blue)
  'hljs-builtin-name': '#005cc5', // 組み込み名 (dark blue)
  'hljs-name': '#22863a',         // 名前 (dark green)
  'hljs-section': '#e36209',      // セクション (dark orange)
  'hljs-tag': '#22863a',          // タグ (dark green)
  'hljs-selector-tag': '#22863a', // セレクタタグ (dark green)
  'hljs-selector-id': '#6f42c1',  // ID セレクタ (dark purple)
  'hljs-selector-class': '#e36209', // クラスセレクタ (dark orange)
  'hljs-selector-attr': '#005cc5',  // 属性セレクタ (dark blue)
  'hljs-selector-pseudo': '#005cc5', // 疑似セレクタ (dark blue)
  'hljs-template-tag': '#24292e',   // テンプレートタグ (black)
  'hljs-template-variable': '#e36209', // テンプレート変数 (dark orange)
  'hljs-addition': '#22863a',       // 追加 (dark green)
  'hljs-deletion': '#d73a49',       // 削除 (dark red)
  'hljs-link': '#005cc5',          // リンク (dark blue)
  'hljs-formula': '#24292e',       // 数式 (black)
  'hljs-quote': '#6a737d',         // 引用 (gray)
  'hljs-bullet': '#e36209',        // 箇条書き (dark orange)
  'hljs-code': '#032f62',          // コード (dark blue)
  'hljs-emphasis': '#24292e',      // 強調 (black)
  'hljs-strong': '#24292e',        // 太字 (black)
};
